version: '3.2'

services:
  web_gateway:
    image: oversort/web-gateway
    ports:
      - '80:80'
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - web

  app_server:
    image: oversort/oversort-server
    ports:
      - '3000:3000'
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 3s
    networks:
      - web

  swarm_viz:
    image: dockersamples/visualizer
    ports:
      - '3001:8080'
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
networks:
  web:
    driver: overlay
