version: '3.1'

services:
  oversort-server:
    image: oversort/oversort-server
    ports:
      - 3000:3000
    deploy:
     mode: replicated
     replicas: 6
     restart_policy:
       max_attempts: 3
       condition: on-failure
     update_config:
       parallelism: 2
       delay: 3s
    networks:
     - web

networks:
  web:
    driver: overlay
