version: '3.2'

services:
  oversort_backend:
    image: oversort/oversort-backend
    ports:
      - '3000:3000'
    environment:
      - OVERSORT_STORE_HOST=192.168.10.2
      - OVERSORT_STORE_PORT=3010
      - OVERSORT_RABBIT_HOST=192.168.10.2
    depends_on:
      - rabbitmq
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        max_attempts: 10
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - web

  swarm_viz:
    image: oversort/swarm-viz
    ports:
      - '3001:8080'
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints:
          - 'node.role == manager'

  cadvisor:
    image: oversort/cadvisor
    ports:
      - target: 8080
        published: 3002
        protocol: tcp
        mode: host
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global

  node-exporter:
    image: oversort/node-exporter
    ports:
      - '9100:9100'
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    deploy:
      mode: global
    networks:
      - web

  swagger:
    image: oversort/swagger
    ports:
      - '3006:8080'
    environment:
      - URLS=[{name:"OverSort Backend", url:"./oversort/jamro-oversort-backend-1.2.0-swagger.json"}, {name:"OverSort Store", url:"./oversort/jamro-oversort-store-1.0.0-swagger.json"}]
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        max_attempts: 10
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - web

  oversort_frontend:
    image: oversort/oversort-frontend
    ports:
      - '3007:80'
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        max_attempts: 10
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - web

  mongo:
    image: oversort/mongo
    ports:
      - 27017:27017
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        max_attempts: 10
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - web

  mongo-express:
    image: oversort/mongo-express
    ports:
      - 3008:8081
    environment:
      - mongo=192.168.10.2
    depends_on:
      - mongo
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        max_attempts: 10
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - web

  rabbitmq:
    image: oversort/rabbitmq
    ports:
      - 5672:5672
      - 3009:15672
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        max_attempts: 10
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - web

  oversort_store:
    image: oversort/oversort-store
    ports:
      - '3010:3000'
    environment:
      - OVERSORT_MONGO_HOST=192.168.10.2
      - OVERSORT_RABBIT_HOST=192.168.10.2
    depends_on:
      - rabbitmq
      - mongo
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        tag: "docker.{{.Name}}"
        fluentd-address: "192.168.10.100:24224"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        max_attempts: 10
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 3s
    networks:
      - web

networks:
  web:
    driver: overlay
