@startuml

  actor User

  autonumber

  activate web_gateway

  == Initialization ==

    User -> web_gateway: GET /
    web_gateway -> oversort_frontend : index.html
    activate oversort_frontend
    oversort_frontend -> web_gateway
    deactivate oversort_frontend
    web_gateway -> User


  == Sort ==

    User -> web_gateway : POST api/sorted
    web_gateway -> oversort_backend
    activate oversort_backend
    oversort_backend -> oversort_backend : sortList = sort()
    oversort_backend -> rabbitmq : send(sortList)
    activate rabbitmq
    oversort_backend -> web_gateway : sortList
    deactivate oversort_backend
    web_gateway -> User
    oversort_store -> rabbitmq : read(sortList)
    activate oversort_store
    deactivate rabbitmq
    oversort_store -> mongo : save(sortList)
    oversort_store -> redis : set(sortList)
    deactivate oversort_store

  == Get History ==

    User -> web_gateway : GET api/history
    web_gateway -> oversort_backend
    activate oversort_backend
    oversort_backend -> oversort_store : GET /sorted
    activate oversort_store
    oversort_store -> redis : get(sortList)
    oversort_store -> mongo : read(sortList)
    oversort_store -> oversort_backend
    deactivate oversort_store
    oversort_backend -> web_gateway
    deactivate oversort_backend
    web_gateway -> User

  deactivate web_gateway

@enduml
