@startuml

title Container Diagram (app)

actor User
node gateway

package "oversort-app" {
  [oversort-frontend]
  [oversort-backend]
  [oversort-store]
  [mongo]
  [redis]
  [rabbitmq]
  [oversort-frontend] --> [oversort-backend]
  [oversort-backend] -right-> [rabbitmq]
  [oversort-backend] --> [oversort-store]
  [rabbitmq] <-- [oversort-store]
  [oversort-store] --> [mongo]
  [oversort-store] -right-> [redis]

}

User --> [gateway]
[gateway] --> [oversort-frontend]

@enduml
