@startuml

title Container Diagram (admin)

actor Admin
node gateway
node infrastructure


package "admin" {
  [admin-panel]
  [cadvisor]
  [grafana]
  [influxdb]
  [node-exporter]
  [prometheus]
}

Admin --> [gateway]
[gateway] --> [admin-panel]
[admin-panel] --> [cadvisor]
[admin-panel] --> [prometheus]
[prometheus] <-down- [cadvisor]
[prometheus] --> [influxdb]
[admin-panel] --> [grafana]
[influxdb] -up-> [grafana]
[node-exporter] -up-> [prometheus]
infrastructure -up-> [cadvisor]
infrastructure -up-> [node-exporter]
@enduml
