[docker-container]@startuml

title Container Diagram (infrastructure)

node app
node admin
node logging
node gateway

package "infrastructure" {
  [infra-swarm-cluster]
  [app-swarm-cluster]
  [vm-infra]
  [vm-manager]
  [vm-worker1]
  [vm-worker2]
}

app <-- [app-swarm-cluster]
admin <-- [app-swarm-cluster]

logging <-- [infra-swarm-cluster]
gateway <-- [infra-swarm-cluster]

[vm-infra] -up-> [infra-swarm-cluster]
[vm-manager] -up-> [app-swarm-cluster]
[vm-worker1] -up-> [app-swarm-cluster]
[vm-worker2] -up-> [app-swarm-cluster]

[Vagrant] -up-> [vm-infra]
[Vagrant] -up-> [vm-manager]
[Vagrant] -up-> [vm-worker1]
[Vagrant] -up-> [vm-worker2]

@enduml
