@startuml

title Container Diagram (app)

actor User
node gateway

package "oversort-app" {
  [oversort-frontend]
  [oversort-backend]
  [mongo]
  [oversort-frontend] --> [oversort-backend]
  [oversort-backend] --> [mongo]

}

User --> [gateway]
[gateway] --> [oversort-frontend]

@enduml
